### ISSUE TITLE
gz sdf always print "Error: SDF parsing the xml failed"

### ISSUE THREAD

**Issue by huweiATgithub** [gazebosim/gz-tools#105]
## Environment
* OS Version:  Ubuntu 20.04
* Source or binary build?
  Binary, it comes with gazebo11.11

## Description
* Expected behavior: Expect to verify an SDF file and provide a useful error message.
* Actual behavior: always complain "Error: SDF parsing the XML failed".

## Steps to reproduce

1. Prepare an SDF file, `model.sdf`,
```XML
<?xml version="1.0"?>
<sdf version="1.5">
  <model name="a_simple_box">
    <static>false</static>
    <link name="link">
      <pose>0 0 1 0 0 0</pose>
      <collision name="collision">
        <geometry>
          <box>
            <size>.3 .2 .5</size>
          </box>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <box>
            <size>.3 .2 .5</size>
          </box>
        </geometry>
      </visual>
    </link>
  </model>
</sdf>
```
to get mentioned error message.
2. Run `gz sdf --verbose -k model.sdf`
3. Run `cp model.sdf modelv.sdf && `gz sdf --verbose -k modelv.sdf` to get "Check complete".

**Comment by azeey** [comment]
Thanks for the issue @huweiATgithub. Since this is an SDFormat issue, would you mind creating the same issue at https://github.com/gazebosim/sdformat?
