### ISSUE TITLE
Failed debbuild of 2.0.0 on Jammy arm64

### ISSUE THREAD

**Issue by scpeters** [gazebosim/gz-tools#114]
## Environment
* OS Version: Ubuntu 22.04 arm64, part of https://github.com/gazebo-tooling/release-tools/issues/578
* Source or binary build? debbuild

## Description
* Expected behavior: Ubuntu 22.04 arm64 debbuild should pass
* Actual behavior: it failed

## Steps to reproduce

1.  Rerun this job: https://build.osrfoundation.org/job/gz-tools2-debbuilder/387/
2.
3.

## Output

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz-tools2-debbuilder&build=387)](https://build.osrfoundation.org/job/gz-tools2-debbuilder/387/) https://build.osrfoundation.org/job/gz-tools2-debbuilder/387/

~~~
[31mautopkgtest [22:52:04]: ERROR: autopkgtest
: error cleaning up:

[0m[31mautopkgtest [22:52:04]: ERROR: testbed failure: timed out on command "env DEBIAN_FRONTEND=noninteractive APT_LISTBUGS_FRONTEND=none APT_LISTCHANGES_FRONTEND=none sh -ec rm -f /etc/apt/sources.list.d/autopkgtest.list /etc/apt/preferences.d/90autopkgtest; (apt-get --quiet update || (sleep 15; apt-get update)) 2>&1" (kind: install)
[0m+ testret=20
+ [[ 20 != 0 ]]
+ [[ 20 != 8 ]]
+ echo 'Problem in running autopkgtest: $testret'
Problem in running autopkgtest: $testret
+ exit 1
~~~

**Comment by azeey** [comment]
Looks like the job passed at some point. I can see the debs at http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gz-tools2/
