### ISSUE TITLE
Make gz-tools a dependency of the packages that use it

### ISSUE THREAD

**Issue by Voldivh** [gazebosim/gz-tools#122]
## Context
I've been working on the development in other packages such as `gz-transport` and `gz-sim`, because of that, I've been building from source everything. If I follow the instructions on the [documentation](https://gazebosim.org/docs/garden/install_ubuntu_src) everything works great. However, there were cases that I didn't build everything (in order to decrease build time) so I used commands like `colcon build --merge-install --packages-up-to gz-transport13`. Those commands work, but, on runtime I got several errors and problems.

The main issue I found out is that several packages uses `gz-tools` package but none of them a direct dependency with it (I also think this is not possible atm), so when I use a flag like `--packages-up-to` that checks the dependencies of the packages, `gz-tools` ends up not being built. 

## Desired behavior

Have a way to create a dependency of `gz-tools` in the other gz packages or at least mention it on the documentation.

## Alternatives considered

1. I tried to simply add the package with a `find_package()` on the CMakeList.txt of the package I was working on, but, that doesn't seem to work and ends up in failure.
2. I'm not sure how an implementation of this would be (or if it is even possible with the package structure). I would say that at least having some documentation regarding this issue would be very helpful. Something like a section saying the following:

- ```md
  ## Building a part of the project
  In case you are trying to build a part of gazebo and not everything take into account that `gz-tools` is a package used
  all over the project but is not a direct dependency of the any of the other packages because of <insert_reason>.
  Therefor, if you encounter issues make sure this package is built or just run:
   `colcon build --merge-install --packages-select gz-tools2`
  ```

**Comment by mjcarroll** [comment]
I think this was intentional?  You could install packages without installing gz-tools at the same time.

**Comment by mjcarroll** [comment]
Yeah, what would be ideal is if we could specify it as a test dependency, rather than a build dependency, because that's what it really is in that situation, correct?

**Comment by Voldivh** [comment]
Well I had issues during test, yeah. However, on examples I drafted this issue also made them crash so I think making it a test dependency only would solve the first case if I'm not wrong.

**Comment by azeey** [comment]
With `package.xml` files added in Harmonic, this is no longer an issue since colcon picks up the dependency from that instead of CMake.
