### ISSUE TITLE
ign tools echo command unable to output data from custom Protobuf messages.

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-tools#5]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-tools/issues/5)) by Nuno Marques (Bitbucket: [TSC21](https://bitbucket.org/%7Ba7356a80-a26a-4ab7-af5b-494fe038a1c7%7D/)).**

----------------------------------------
# Prerequisites
    * [X] Checked the Q&A board for common solutions: http://answers.gazebosim.org
    * [X] Checked that your issue isn't already filed.
    * [X] Checked that there is not already an Ignition package that provides the described functionality: https://ignitionrobotics.org/libs

# Description 

I set up a publisher using ignition Transport Publisher in a plugin and, in another plugin, I setup the Subscriber, also from ignition Transport. I can see that the data is exchanged between the plugins, though, using `ign-tools`, more in specific, the echo tool, I am not able to echo any data coming from the publisher.

The publisher is setup like the following:
```c++
ignition::transport::Node::Publisher m_baro_pub_ign_;
...
m_baro_pub_ign_ = node_ign_.Advertise<sensor_msgs::msgs::Baro>("/gazebo/default/" + m_model->GetName() + m_baro_topic);
...
m_baro_pub_ign_.Publish(msg);
```

the subscriber is setup as follows:
```
node_ign_.Subscribe("/gazebo/default/" + model_->GetName() + baro_sub_topic_, &GazeboMotorModel::BaroCallback_, this)

void GazeboMotorModel::BaroCallback_(const sensor_msgs::msgs::Baro &baro_msg)
{
  ...
} tried to follow your suggestion on using ignition Transport. tried to follow your suggestion on using ignition Transport.
```

If I try to echo the topic using `ign topic --echo -t /gazebo/default/<model_name>/baro`, nothing is echoed, which leads me to think that the `ign-tools` is not able to process custom protobuf messages, same as `gz-tools`.

Also another note: I am not able to plug a Gazebo Transport publisher with a ignition Transport subscriber and vice-versa, using a custom protobuf messages, so that's why I decided to apply a publisher and a subscriber of the same type (ignition Transport). So I question the compatibility between the legacy Gazebo transport and the ignition Tranport for custom messages.

@chapulina Any tip you can give here?

# Steps to Reproduce

The steps to reproduce are as simple as creating a publisher and a subscriber for a custom protobuf message and then try to use `ign topic --echo -t  <topic/path>`.

**Expected behavior:**  

I am expecting to have the topic data being echoed on the console.

**Actual behavior:**

Nothing really happens (doesn't crash but doesn't output anything as well).

**Reproduces how often:** 

Always. And this was also confirmed by another used before: http://answers.gazebosim.org/question/17148/how-to-make-the-ign-tool-work-with-custom-messages/

# Versions

Ubuntu 18.04, Gazebo 9, ignition Transport 4.0.0, ignition tools 4.0.0 installed from debs. The only thing that is built from source is the custom written plugins for Gazebo.

# Additional Information

This was already reported for discussion in https://bitbucket.org/osrf/gazebo/issues/2569/support-for-self-describing-messages, but came out from another context, even though the purpose is the same: being able to echo topics (Gazebo/Ign) using echo commands from tools.

**Comment by azeey** [comment]
This was fixed in gz-msgs10 with [this](https://gazebosim.org/api/msgs/10/messagegeneration.html) tutorial that covers custom message generation.
